name: resumeFlutterApp
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.5.0
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: YanoneKaffeesatz
      fonts:
        - asset: fonts/YanoneKaffeesatz-Regular.ttf
          weight: 400
        - asset: fonts/YanoneKaffeesatz-Bold.ttf
          weight: 700